version: "2"
linters:
  enable:
    - bodyclose
    - durationcheck
    - errorlint
    - gocritic
    - gosec
    - misspell
    - nakedret
    - nolintlint
    - revive
    - unconvert
    - unparam
  settings:
    revive:
      confidence: 0
      rules:
        - name: var-naming
          disabled: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - .*\.pb\.go
      - testdata$
      - test/mock
      - third_party$
      - builtin$
      - examples$
    rules:
      # Exclude some linters from running on tests files.
      - path: _test\.go
        linters:
          - gocyclo
          - errcheck
          - dupl
          - gosec
formatters:
  enable:
    - goimports
  exclusions:
    generated: lax
    paths:
      - .*\.pb\.go
      - testdata$
      - test/mock
      - third_party$
      - builtin$
      - examples$