apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "command-cert-manager-issuer.labels" . | nindent 4 }}
  name: {{ include "command-cert-manager-issuer.name" . }}-manager-role
rules:
  - apiGroups:
      - cert-manager.io
    resources:
      - certificaterequests
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - cert-manager.io
    resources:
      - certificaterequests/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - command-issuer.keyfactor.com
    resources:
      - clusterissuers
      - issuers
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - command-issuer.keyfactor.com
    resources:
      - clusterissuers/status
      - issuers/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - command-issuer.keyfactor.com
    resources:
      - issuers/finalizers
    verbs:
      - update
