apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "command-cert-manager-issuer.labels" . | nindent 4 }}
  name: {{ include "command-cert-manager-issuer.name" . }}-manager-role
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - cert-manager.io
    resources:
      - certificaterequests
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - cert-manager.io
    resources:
      - certificaterequests/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - command-issuer.keyfactor.com
    resources:
      - clusterissuers
      - issuers
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - command-issuer.keyfactor.com
    resources:
      - clusterissuers/status
      - issuers/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - command-issuer.keyfactor.com
    resources:
      - issuers/finalizers
    verbs:
      - update
{{- if .Values.secureMetrics.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "command-cert-manager-issuer.labels" . | nindent 4 }}
  name: {{ include "command-cert-manager-issuer.name" . }}-proxy-role
rules:
  - apiGroups:
      - authentication.k8s.io
    resources:
      - tokenreviews
    verbs:
      - create
  - apiGroups:
      - authorization.k8s.io
    resources:
      - subjectaccessreviews
    verbs:
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "command-cert-manager-issuer.labels" . | nindent 4 }}
  name: {{ include "command-cert-manager-issuer.name" . }}-metrics-reader
rules:
  - nonResourceURLs:
      - /metrics
    verbs:
      - get
{{- end }}