{{- if .Values.metrics.secure }}
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "command-cert-manager-issuer.labels" . | nindent 4 }}
  name: {{ include "command-cert-manager-issuer.name" . }}-metrics-service
spec:
  ports:
    - name: https
      port: 8443
      protocol: TCP
      targetPort: https
  selector:
    {{- include "command-cert-manager-issuer.selectorLabels" . | nindent 4 }}
{{- end}}