name: Package and Release Helm Chart
on:
  pull_request:
    branches:
      - 'v*'
    types:
      # action should run when the pull request is closed
      # (regardless of whether it was merged or just closed)
      - closed

jobs:
  helm:
    name: Package and Release Helm Chart
    runs-on: ubuntu-latest

    # Restrict to only run if the PR is merged
    if: github.event.pull_request.merged == true

    steps:
      # Set the IMAGE_NAME environment variable to the repository name
      # Use parameter expansion to convert to lowercase
      - name: Set IMAGE_NAME
        run: |
          echo "IMAGE_NAME=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      # Set the CHART_NAME environment variable to the repository name
      # IMAGE_NAME is in the format owner/repo, so use parameter expansion to get the repo name
      - name: Set CHART_NAME
        run: |
          echo "CHART_NAME=${IMAGE_NAME##*/}" >>${GITHUB_ENV}

      # Checkout code
      # https://github.com/actions/checkout
      - name: Checkout code
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0

      # Extract metadata (tags, labels) to use in Helm chart
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@96383f45573cb7f253c731d3b3ab81c87ef81934 # v5.0.0
        with:
          images: ${{ env.IMAGE_NAME }}

      # Set version from DOCKER_METADATA_OUTPUT_VERSION as environment variable
      # This workflow is triggered when PRs with semver tags are closed, so
      # DOCKER_METADATA_OUTPUT_VERSION will be in the format `v1.2(.3)`
      - name: Set Version
        run: |
          echo "VERSION=${DOCKER_METADATA_OUTPUT_VERSION:1}" >> $GITHUB_ENV

      # Change version and appVersion in Chart.yaml to the tag in the closed PR
      - name: Update Helm App/Chart Version
        shell: bash
        run: |
          sed -i "s/^version: .*/version: ${{ env.VERSION }}/g" deploy/charts/${{ env.CHART_NAME }}/Chart.yaml
          sed -i "s/^appVersion: .*/appVersion: \"${{ env.DOCKER_METADATA_OUTPUT_VERSION }}\"/g" deploy/charts/${{ env.CHART_NAME }}/Chart.yaml

      # Setup Helm
      # https://github.com/Azure/setup-helm
      - name: Install Helm
        uses: azure/setup-helm@5119fcb9089d432beecbf79bb2c7915207344b78 # v3.5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      # Helm requires an ident name to be set for chart-releaser to work
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      # Build and release Helm chart to GitHub Pages
      # https://github.com/helm/chart-releaser-action
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@be16258da8010256c6e82849661221415f031968 # v1.5.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          charts_dir: deploy/charts

      # Create GitHub tag with Container version to kick off container release workflow
      # https://github.com/actions/github-script
      - name: Create new tag to kick off container release
        uses: actions/github-script@d7906e4ad0b1822421a7e6a35d5ca353c962f410 # v6.4.1
        with:
          github-token: ${{ secrets.TOKEN }}
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/' + process.env.DOCKER_METADATA_OUTPUT_VERSION,
              sha: context.sha
            })