name: test
on: [workflow_dispatch, push, pull_request]
jobs:
  build:
    name: Build and Lint
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      # Checkout code
      # https://github.com/actions/checkout
      - name: Checkout code
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0

      # Setup GoLang build environment
      # https://github.com/actions/setup-go
      - name: Set up Go 1.x
        uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
        with:
          go-version-file: 'go.mod'
          cache: true

      # Download dependencies
      - run: go mod download

      # Build Go binary
      - run: go build -v .

      # Run Go linters
      # https://github.com/golangci/golangci-lint-action
      - name: Run linters
        uses: golangci/golangci-lint-action@3a919529898de77ec3da873e3063ca4b10e7f5cc # v3.7.0
        with:
          version: latest

  test:
    name: Go Test
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      # Checkout code
      # https://github.com/actions/checkout
      - name: Checkout code
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0

      # Setup GoLang build environment
      # https://github.com/actions/setup-go
      - name: Set up Go 1.x
        uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
        with:
          go-version-file: 'go.mod'
          cache: true

      # Download dependencies
      - run: go mod download

      # Run Go tests
      - env:
          COMMAND_CERTIFICATE_AUTHORITY_HOSTNAME: ${{ secrets.COMMAND_CERTIFICATE_AUTHORITY_HOSTNAME }}
          COMMAND_CERTIFICATE_AUTHORITY_LOGICAL_NAME: ${{ secrets.COMMAND_CERTIFICATE_AUTHORITY_LOGICAL_NAME }}
          COMMAND_CERTIFICATE_TEMPLATE: ${{ secrets.COMMAND_CERTIFICATE_TEMPLATE }}
          COMMAND_HOSTNAME: ${{ secrets.COMMAND_HOSTNAME }}
          COMMAND_USERNAME: ${{ secrets.COMMAND_USERNAME }}
          COMMAND_PASSWORD: ${{ secrets.COMMAND_PASSWORD }}
        name: Run go test
        run: go test -v ./...