name: Build and Test
on:
    pull_request:
        types: [opened, synchronize, reopened]
    push:
        branches:
        - 'main'
        - 'release-*.*'
jobs:
  build:
    name: Build and Lint
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      # Checkout code
      # https://github.com/actions/checkout
      - name: Checkout code
        uses: actions/checkout@v5

      # Setup GoLang build environment
      # https://github.com/actions/setup-go
      - name: Set up Go 1.x
        uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
          cache: true

      # Download dependencies
      - run: go mod download

      # Build Go binary
      - run: go build -v cmd/main.go

      # Run Go linters
      # https://github.com/golangci/golangci-lint-action
      - name: Run linters
        uses: golangci/golangci-lint-action@v7
        with:
          version: v2.4.0

      - name: Regenerate CRDs
        run: make generate manifests
      - name: Check for CRD drift
        run: |
          git diff --compact-summary --exit-code || \
            (echo; echo "Unexpected difference in directories after code generation. Run 'make generate manifests' and commit."; exit 1)

  test:
    name: Go Test
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      # Checkout code
      # https://github.com/actions/checkout
      - name: Checkout code
        uses: actions/checkout@v5

      # Setup GoLang build environment
      # https://github.com/actions/setup-go
      - name: Set up Go 1.x
        uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
          cache: true

      # Run Go tests
      - name: Run go test
        run: go test -v ./...