name: Build Test and Lint
on:
    workflow_dispatch:
    pull_request:
    push:
        branches:
        - 'main'
        - 'release-*.*'
jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      # Checkout code
      # https://github.com/actions/checkout
      - name: Checkout code
        uses: actions/checkout@v5

      # Setup GoLang build environment
      # https://github.com/actions/setup-go
      - name: Set up Go 1.x
        uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
          cache: true

      # Download dependencies
      - run: go mod download

      # Build Go binary
      - run: go build -v cmd/main.go

      - run: go test ./...

  lint:
    name: Lint
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      # Checkout code
      # https://github.com/actions/checkout
      - name: Checkout code
        uses: actions/checkout@v5

      # Setup GoLang build environment
      # https://github.com/actions/setup-go
      - name: Set up Go 1.x
        uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
          cache: true

      - name: Install Helm
        uses: azure/setup-helm@v3.5

      # Run Go linters
      # https://github.com/golangci/golangci-lint-action
      - name: Run linters
        uses: golangci/golangci-lint-action@v7
        with:
          version: v2.4.0

      - name: Regenerate CRDs
        run: make generate manifests
    
      - name: Check for CRD drift
        run: |
          git diff --compact-summary --exit-code -- config/crd deploy/charts || \
            (echo; echo "Unexpected difference in directories after code generation. Run 'make generate manifests' and commit."; exit 1)

      - name: Lint Helm manifests
        run: make lint-manifests

  dependency-review:
    name: Dependency Review
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Dependency Review
        uses: actions/dependency-review-action@v5
        with:
          fail-on-severity: critical
